# Graded: 7 of 7 correct
- [x] Array `A`: (3,3) random ints
- [x] Array `b`: (3,) random ints
- [x] `A * b`
- [x] Explanation of `A * b`: show broadcast versions
- [x] Array `c`: (2,) random ints
- [x] `A * c`
- [x] Explanation of `A * c`

Comments:


## Unit 5 Numpy_Broadcast Quiz
* The objective of this quiz is to understand how to use how broadcasting works with Numpy arrays.

In [12]:
## Import Numpy and check version
import numpy as np
from IPython.display import Latex as lt

# Room_length [m]

print(f"Numpy version is {np.__version__}")

<IPython.core.display.Latex object>
Numpy version is 1.26.4


***
## Broadcasting is a feature of Numpy arrays that allows arithmetic operations between arrays that are not necessarily of compatible dimension for the computation.
* During such an operation, the arrays are "broadcast" to a certain size that makes the operartion possible.
* Knowledge of broadcasting is useful in a number of places, for example deep learning methids.

## Create  a Numpy array `A` as a (3, 3) array of random integers.

In [6]:
# Your code here
A = np.random.randint(0,10,size=[3,3])
print(A)



[[6 5 9]
 [6 7 1]
 [9 6 4]]


## Create a second numpy array, `b` of size (3,) of random integers.

In [8]:
# Your code here
b = np.random.randint(0, 10, size=[ 3])
print(b)

[8 0 9]


## Perform the operation `A*b`

In [30]:
# Your code below
print(A*b)


[[48  0 81]
 [48  0  9]
 [72  0 36]]
[129  57 108]


***
## Explain why it was possible to compute `A*b` in the above case. 
* As part of your explanation, show the broadcast versions of `A` and `b`

### Explanation here.
The multiplication becomes possible due to `broadcasting`, which supplements a scalar value across n-dimensions to make multiplication possible. To demonstrate: 

$$
\begin{bmatrix}
6 & 5 & 9 \\
6 & 7 & 1 \\
9 & 6  & 4
\end{bmatrix}
*
\begin{bmatrix}
8 & 0 & 9 
\end{bmatrix}
$$

Becomes the below operation: 
$$
\begin{bmatrix}
6 & 5 & 9 \\
6 & 7 & 1 \\
9 & 6  & 4
\end{bmatrix}
*
\begin{bmatrix}
8 & 0 & 9 \\
8 & 0 & 9 \\
8 & 0 & 9 
\end{bmatrix}
$$

Which we can see due to the result operation being:
$$
\begin{bmatrix}
48 & 0 & 81 \\
 48 & 0 & 9 \\
 72 & 0 & 36
\end{bmatrix}
$$

#### Note:
This is **not** complete matrix multiplication, to perform complete multiplication `np.matmul(A, b)` should be used instead, which would get you the correct answer as shown below. 

In [31]:
print(np.matmul(A, b))

[129  57 108]


$$
\begin{bmatrix}
48 & 0 & 81 \\
 48 & 0 & 9 \\
 72 & 0 & 36
\end{bmatrix}
$$

Where if we sum together all the rows, we get the expected output of a 3x3 * 3x1 matrix. 

$$
\begin{bmatrix}
 129 & 57 & 108
\end{bmatrix}
$$


***
## Now create a third array `c` that is a (2,) array of random integers.

In [19]:
# Your code here
c = np.random.randint(0, 10, size=[2,])
print(c)

[6 1]


## Perform the operation `A*c`

In [20]:
# Your code here
print(A*c)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

***
## Explain, in terms of broadcasting, why it was not possible to compute `A*c`

### Your explanation here.

Numpy considers matrix compatibility (for broadcasting) off of two rules; two dimensions are compatible when,

1. they are equal, or
2. one of them is 1.

as `c = [2,]` and `A = [3, 3]`their sizes are incompatible and `c` cannot be stretched to fit accordingly. To demonstrate: 

$$
\begin{bmatrix}
6 & 5 & 9 \\
6 & 7 & 1 \\
9 & 6  & 4
\end{bmatrix}
*
\begin{bmatrix}
6 & 1  
\end{bmatrix}
$$

Becomes the below operation: 
$$
\begin{bmatrix}
6 & 5 & 9 \\
6 & 7 & 1 \\
9 & 6  & 4
\end{bmatrix}
*
\begin{bmatrix}
6 & 1  \\
6 & 1  \\
6 & 1  
\end{bmatrix}
$$

Which **is possible** for matrix multiplication, but **not broadcasting**. It's a bit confusing since the stretched values of c results in a dimension of `c = 2x3`, with `c` having 3 rows, it is compatible for `A = 3x3` as it has only 3 columns. This case, you'd want to use `np.matmul()`, however that also doesn't work since the function doesn't perform broadcasting. 




In [34]:
print(np.matmul(A,c))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

Now what if we were to implement that broadcasting ourselves? 

In [53]:
# Get the number of columns for the first matrix (A)
col = A.shape[1]

# broadcast with a place holder array of 0s based off column of first matrix
# i is a disposable array of 0s
c_b, i = np.broadcast_arrays(c, np.zeros(shape=[col,1])) # we want the number of rows to match, so we need to scale the rows of c by the number of columns of A

# Now perform matrix multiplication 
print(np.matmul(A, c_b))



[[120  20]
 [ 84  14]
 [114  19]]


This being said, I don't know if it necessary serves any purpose, as you're generating data that doesn't exist. This was more just a thought experiment and trying to see how the broadcasting feature worked. 