## Unit 5 Numpy_Random_Matrix Quiz
* The objective of this quiz is to use Numpy for generating random values and look at simple array manipulation.

In [1]:
## Import Numpy and check version
import numpy as np
print(f"Numpy version is {np.__version__}")

Numpy version is 1.26.4


### Random numbers are frequently used in Data Science.
* Generating random numbers (or rather pseudo-random numbers) is an important function.
* Numpy provides a random number module called `numpy.random`.
* You can learn more about generating random numbers [here](https://numpy.org/doc/stable/reference/random/index.html) and [here](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random).

### Create a random number generator called `my_rng` using the `default_rng()` method in `np.random`. Use the default seed.

In [59]:
# Write your code below.
#def my_rng(r = 1,c = 1, num1 = 0, num2 = 2):
#   rng = np.random.default_rng()
#   return rng.integers(low = num1, high = num2, size=[r,c])

#def my_rng(r = 1, c = 1, num1 = 0, num2 = 2):
#    np.random.default_rng()
#    return np.random.rand(r,c)

def my_rng(r = 1, c = 1, num1 = 0, num2 = 2):
    np.random.default_rng()
    return np.random.uniform(low=num1, high=num2, size = [r,c])

# it took me too long to realize I was just supposed to do this
my_rng = np.random.default_rng()

### Now use `my_rng` to generate a 3X3 numpy array of random values.
* Print out this array

In [56]:
# Write your code below.
print(my_rng(3,3))

[[0.93408663 0.57249503 0.74259829]
 [0.22236197 0.98081689 0.43966015]
 [0.5627087  0.78953752 0.87843753]]


### What is the distribution of the random numbers generated and what is the range?
* This is not something to be computed, simply look up this information in the [`np.random` web page](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html).

Creates an array of the given shape and populate it with random samples from a **uniform distribution** over [0,1], thus we can use `np.random.uniform` for the question below.


### Use the Numpy array created above to create a second Numpy array of random numbers that is between -10.0 and 10.0.
* This question requires you to figure out the mapping that will convert a set of random numbers that are distributed as found in the previous question to have the range from -10.0 to 10.0.
* The form of the distributon does not change.

In [58]:
# Show your code below.
print(my_rng(3,3,-10,10))

[[-8.51571628 -1.44831582 -2.74253647]
 [-8.84337472  7.01019185  5.35380599]
 [ 4.00802138  4.92393026 -6.03844156]]


### `np.random` can also generate random integers. Generate a 3X3 array of random integers between 0 and 10.

In [61]:
# Your code here.
print(np.random.randint(0, 10, [3, 3] ))

[[2 0 1]
 [9 2 3]
 [2 3 4]]


### `np.random` can also generate various common distributions. Generate a 3X3 array of numbers from a normal distribution with mean 10 and standard deviation 2.

In [64]:
# Your code here
gm3 = np.random.normal(10, 2, [3, 3])
print(gm3)

[[ 7.07308865 10.79450086  6.4274544 ]
 [ 8.7938588   7.09250144 13.34681276]
 [10.98958341  7.14865853 12.30993312]]


### Call the 3X3 matrix of normal random variables generated in the last step `gm3`.
* Use Numpy methods to create two other numpy arrays, `row_sum` and `col_sum`:
* `row_sum` should be the length 3 array of the sum of the rows of `gm3`.
* `col_sum` should be the length 3 array of the sum of the columns of `gm3`

In [72]:
# Your code here
row_sum = np.sum(gm3, 1)
col_sum = np.sum(gm3, 0)
print(f'Sum of the rows of gm3: {row_sum}\nSum of the colums of gm3: {col_sum}\n')

# check work
r1 = 7.07308865 + 10.79450086 + 6.4274544
c1 = 7.07308865 + 8.7938588 + 10.98958341
print(f'Row 1 sum: {r1}\nCol 1 sum: {c1}')


Sum of the rows of gm3: [24.29504391 29.23317301 30.44817506]
Sum of the colums of gm3: [26.85653087 25.03566083 32.08420029]

Row 1 sum: 24.295043909999997
Col 1 sum: 26.85653086
